"""
Spotify Service for API integration.
"""
from typing import Dict, List, Optional
import time
import hashlib
import json

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

from app.core.config import settings
from loguru import logger

from .spotify_modules.search import SearchMixin
from .spotify_modules.recommendations import RecommendationsMixin
from .spotify_modules.user_profile import UserProfileMixin
from .spotify_modules.playlist import PlaylistMixin
from .spotify_modules.audio_features import AudioFeaturesMixin

import asyncio


class SpotifyService(
    SearchMixin,
    RecommendationsMixin,
    UserProfileMixin,
    PlaylistMixin,
    AudioFeaturesMixin
):
    """Service for Spotify API operations."""

    def __init__(self):
        """Initialize Spotify client credentials."""
        # Validate credentials are set
        if (not settings.SPOTIFY_CLIENT_ID or
                not settings.SPOTIFY_CLIENT_SECRET):
            logger.error("Spotify credentials are missing!")
            raise ValueError(
                "SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET must be set"
            )

        # Log partial credentials for debugging (first 10 chars only)
        secret_display = (
            "*" * 10 if settings.SPOTIFY_CLIENT_SECRET else "MISSING"
        )
        logger.debug(
            f"Spotify Client ID: {settings.SPOTIFY_CLIENT_ID[:10]}... "
            f"Secret: {secret_display}"
        )
        self.client_credentials = SpotifyClientCredentials(
            client_id=settings.SPOTIFY_CLIENT_ID,
            client_secret=settings.SPOTIFY_CLIENT_SECRET,
        )

        # In-memory cache for optimized methods
        self._cache = {}
        self._cache_ttl = 3600  # 1 hour

        logger.info("SpotifyService initialized")

    def get_user_client(self, access_token: str) -> spotipy.Spotify:
        """
        Get Spotify client with user's access token.

        Args:
            access_token: User's Spotify access token

        Returns:
            Authenticated Spotify client
        """
        return spotipy.Spotify(auth=access_token)

    async def get_user_top_tracks(
        self,
        user_client: spotipy.Spotify,
        limit: int = 50,
    ) -> List[Dict]:
        """
        Get user's top tracks.

        Args:
            user_client: Authenticated Spotify client
            limit: Number of tracks to retrieve

        Returns:
            List of track dictionaries
        """
        try:
            results = user_client.current_user_top_tracks(
                limit=limit, time_range="medium_term"
            )
            return results.get("items", [])
        except Exception as e:
            logger.error(f"Failed to get user top tracks: {e}")
            raise

    async def get_user_top_artists(
        self,
        user_client: spotipy.Spotify,
        limit: int = 20,
    ) -> List[Dict]:
        """
        Get user's top artists.

        Args:
            user_client: Authenticated Spotify client
            limit: Number of artists to retrieve

        Returns:
            List of artist dictionaries
        """
        try:
            results = user_client.current_user_top_artists(
                limit=limit, time_range="medium_term"
            )
            return results.get("items", [])
        except Exception as e:
            logger.error(f"Failed to get user top artists: {e}")
            raise

    async def create_playlist(
        self,
        user_client: spotipy.Spotify,
        user_id: str,
        name: str,
        tracks: List[str],  # Spotify URIs
        description: str = "Generated by RunBeat AI",
    ) -> Dict:
        """
        Create playlist in user's Spotify account.

        Args:
            user_client: Authenticated Spotify client
            user_id: Spotify user ID
            name: Playlist name
            tracks: List of Spotify track URIs
            description: Playlist description

        Returns:
            Dictionary with playlist ID, URL, and URI
        """
        try:
            # Create playlist
            playlist = user_client.user_playlist_create(
                user=user_id,
                name=name,
                public=False,
                description=description,
            )

            # Add tracks in batches (max 100 per request)
            if tracks:
                for i in range(0, len(tracks), 100):
                    batch = tracks[i: i + 100]
                    user_client.playlist_add_items(
                        playlist_id=playlist["id"],
                        items=batch,
                    )

            return {
                "id": playlist["id"],
                "url": playlist["external_urls"]["spotify"],
                "uri": playlist["uri"],
            }

        except Exception as e:
            logger.error(f"Failed to create playlist: {e}")
            raise

    # ========== OPTIMIZED METHODS ==========
    # These methods provide better performance with User Authorization
    # and caching support

    def _get_cache_key(
        self,
        seed_genres: List[str],
        min_tempo: int,
        max_tempo: int,
        target_energy: float,
        user_token: Optional[str] = None
    ) -> str:
        """Generate cache key from parameters."""
        key_data = {
            "genres": sorted(seed_genres) if seed_genres else [],
            "min_tempo": min_tempo,
            "max_tempo": max_tempo,
            "target_energy": target_energy,
            "user_token": bool(user_token)  # Don't cache token itself
        }
        key_str = json.dumps(key_data, sort_keys=True)
        return hashlib.md5(key_str.encode()).hexdigest()

    async def get_seed_tracks_from_genres(
        self,
        genres: List[str],
        limit_per_genre: int = 5,
        user_token: Optional[str] = None
    ) -> List[str]:
        """
        Отримати seed tracks з жанрів (оптимізовано з паралельними запитами).

        Args:
            genres: Список жанрів
            limit_per_genre: Кількість треків на жанр
            user_token: User access token (опціонально)

        Returns:
            Список track IDs для використання як seeds
        """
        import asyncio

        genres = genres[:2] if genres else []
        if not genres:
            return []

        # Перевірка кешу
        cache_key = f"seed_tracks_{hash(tuple(sorted(genres)))}_{limit_per_genre}"
        if cache_key in self._cache:
            cached_data, timestamp = self._cache[cache_key]
            if time.time() - timestamp < 1800:  # 30 хвилин для seed tracks
                logger.debug(f"Cache hit for seed tracks: {genres}")
                return cached_data

        # Використовуємо User Auth якщо доступний, інакше Client Credentials
        if user_token:
            sp = spotipy.Spotify(auth=user_token)
        else:
            sp = spotipy.Spotify(
                client_credentials_manager=self.client_credentials
            )

        genre_map = {
            "pop": "pop music",
            "rock": "rock music",
            "electronic": "electronic music",
            "hip-hop": "hip hop",
            "country": "country music",
            "house": "house music",
            "techno": "techno music",
            "dance": "dance music",
            "r&b": "r&b music",
            "jazz": "jazz music",
            "edm": "edm music",
            "trance": "trance music",
        }

        # OPTIMIZATION: Паралельні запити для всіх жанрів одночасно
        async def search_genre(genre: str) -> List[str]:
            """Пошук треків для одного жанру."""
            try:
                search_term = genre_map.get(genre.lower(), genre)
                # Використовуємо run_in_executor для неблокуючих запитів
                loop = asyncio.get_event_loop()
                search_results = await loop.run_in_executor(
                    None,
                    lambda: sp.search(
                        q=search_term,
                        type="track",
                        limit=limit_per_genre,
                        market="US"
                    )
                )
                tracks = search_results.get("tracks", {}).get("items", [])
                return [track["id"] for track in tracks if track.get("id")]
            except Exception as e:
                logger.debug(f"Failed to get seed tracks for {genre}: {e}")
                return []

        # Виконуємо всі запити паралельно
        try:
            results = await asyncio.gather(*[search_genre(g) for g in genres])
            seed_tracks = []
            seen_ids = set()

            # Об'єднуємо результати, уникаючи дублікатів
            for track_ids in results:
                for track_id in track_ids:
                    if track_id not in seen_ids:
                        seed_tracks.append(track_id)
                        seen_ids.add(track_id)
                        if len(seed_tracks) >= 5:
                            break
                if len(seed_tracks) >= 5:
                    break
        except Exception as e:
            logger.warning(
                f"Parallel seed tracks search failed: {e}, falling back to sequential")
            # Fallback до послідовного пошуку
            seed_tracks = []
            for genre in genres:
                try:
                    search_term = genre_map.get(genre.lower(), genre)
                    search_results = sp.search(
                        q=search_term,
                        type="track",
                        limit=limit_per_genre,
                        market="US"
                    )
                    tracks = search_results.get("tracks", {}).get("items", [])
                    for track in tracks:
                        if track.get("id") and track["id"] not in seed_tracks:
                            seed_tracks.append(track["id"])
                            if len(seed_tracks) >= 5:
                                break
                    if len(seed_tracks) >= 5:
                        break
                except Exception as e:
                    logger.warning(
                        f"Failed to get seed tracks for {genre}: {e}")
                    continue

        result = seed_tracks[:5]  # Max 5 seeds

        # Зберегти в кеш
        self._cache[cache_key] = (result, time.time())

        return result

    async def get_recommendations_optimized(
        self,
        seed_genres: List[str],
        seed_artists: List[str],
        target_tempo: int,
        min_tempo: int,
        max_tempo: int,
        target_energy: float,
        limit: int = 20,
        user_token: Optional[str] = None,
        use_cache: bool = True
    ) -> List[Dict]:
        """
        Оптимізований метод отримання рекомендацій.

        Strategy:
        1. Перевірка кешу
        2. Використання User Auth для Recommendations API
        3. Fallback до Search API з Client Credentials
        4. Batch запити для audio features
        """
        # Перевірка кешу
        if use_cache:
            cache_key = self._get_cache_key(
                seed_genres, min_tempo, max_tempo, target_energy, user_token
            )
            if cache_key in self._cache:
                cached_data, timestamp = self._cache[cache_key]
                if time.time() - timestamp < self._cache_ttl:
                    logger.debug(f"Cache hit for key: {cache_key}")
                    return cached_data[:limit]

        # Strategy 1: Recommendations API з User Auth
        if user_token:
            try:
                sp = spotipy.Spotify(auth=user_token)

                # Отримати seed tracks
                seed_tracks = await self.get_seed_tracks_from_genres(
                    seed_genres, user_token=user_token
                )

                if seed_tracks:
                    rec_params = {
                        "seed_tracks": seed_tracks[:5],
                        "min_tempo": min_tempo,
                        "max_tempo": max_tempo,
                        "target_energy": target_energy,
                        "limit": limit
                    }
                else:
                    rec_params = {
                        "seed_genres": seed_genres[:2] if seed_genres else ["pop"],
                        "min_tempo": min_tempo,
                        "max_tempo": max_tempo,
                        "target_energy": target_energy,
                        "limit": limit
                    }

                logger.debug(f"Using Recommendations API with User Auth")
                results = sp.recommendations(**rec_params)
                tracks = results.get("tracks", [])

                if tracks:
                    # Отримати audio features batch
                    track_ids = [t["id"] for t in tracks if t.get("id")]
                    features = await self.get_audio_features_batch_optimized(
                        track_ids, user_token=user_token
                    )

                    # Merge features with tracks
                    for i, track in enumerate(tracks):
                        if i < len(features) and features[i]:
                            track.update(features[i])

                    # Зберегти в кеш
                    if use_cache:
                        self._cache[cache_key] = (tracks, time.time())

                    return tracks

            except Exception as e:
                logger.warning(
                    f"Recommendations API with User Auth failed: {e}, "
                    "falling back to Search API"
                )

        # Strategy 2: Search API з Client Credentials (fallback)
        logger.debug("Using Search API with Client Credentials")
        tracks = await self.get_tracks_by_search_optimized(
            seed_genres=seed_genres,
            min_tempo=min_tempo,
            max_tempo=max_tempo,
            target_energy=target_energy,
            limit=limit
        )

        # Зберегти в кеш
        if use_cache and tracks:
            cache_key = self._get_cache_key(
                seed_genres, min_tempo, max_tempo, target_energy, user_token
            )
            self._cache[cache_key] = (tracks, time.time())

        return tracks

    async def get_audio_features_batch_optimized(
        self,
        track_ids: List[str],
        batch_size: int = 100,
        user_token: Optional[str] = None
    ) -> List[Optional[Dict]]:
        """
        Оптимізований batch запит для audio features з паралельними запитами.

        Spotify API дозволяє до 100 треків в одному запиті.
        OPTIMIZATION: Паралельна обробка батчів для швидшої роботи.
        """
        import asyncio

        if not track_ids:
            return []

        batch_size = min(batch_size, 100)  # Spotify limit

        # Перевірка кешу
        # Перші 50 для ключа
        cache_key = f"audio_features_{hash(tuple(track_ids[:50]))}"
        if cache_key in self._cache:
            cached_data, timestamp = self._cache[cache_key]
            if time.time() - timestamp < 3600:  # 1 година для audio features
                logger.debug(
                    f"Cache hit for audio features: {len(track_ids)} tracks")
                return cached_data

        # Використовуємо User Auth якщо доступний
        if user_token:
            sp = spotipy.Spotify(auth=user_token)
        else:
            sp = spotipy.Spotify(
                client_credentials_manager=self.client_credentials
            )

        # OPTIMIZATION: Паралельна обробка батчів
        async def fetch_batch(batch: List[str], batch_num: int) -> List[Optional[Dict]]:
            """Отримати audio features для одного батчу."""
            try:
                loop = asyncio.get_event_loop()
                batch_features = await loop.run_in_executor(
                    None,
                    lambda: sp.audio_features(batch)
                )
                if batch_features:
                    return batch_features
                else:
                    return [None] * len(batch)
            except Exception as e:
                error_str = str(e).lower()
                if "403" in error_str or "forbidden" in error_str:
                    logger.warning(
                        f"Audio features API returned 403 for batch {batch_num}. "
                        "This may indicate insufficient permissions."
                    )
                elif "429" in error_str or "rate limit" in error_str:
                    logger.warning(
                        f"Rate limit hit for batch {batch_num}, waiting 1s...")
                    await asyncio.sleep(1)
                    # Retry once
                    try:
                        loop = asyncio.get_event_loop()
                        batch_features = await loop.run_in_executor(
                            None,
                            lambda: sp.audio_features(batch)
                        )
                        return batch_features if batch_features else [None] * len(batch)
                    except Exception as retry_error:
                        logger.warning(
                            f"Retry failed for batch {batch_num}: {retry_error}")
                else:
                    logger.warning(f"Batch {batch_num} failed: {e}")
                return [None] * len(batch)

        # Розбиваємо на батчі та виконуємо паралельно
        batches = [track_ids[i:i + batch_size]
                   for i in range(0, len(track_ids), batch_size)]

        try:
            # Виконуємо всі батчі паралельно (але обмежуємо до 3 одночасно для rate limits)
            features = []
            semaphore = asyncio.Semaphore(3)  # Максимум 3 паралельні запити

            async def fetch_with_semaphore(batch: List[str], batch_num: int):
                async with semaphore:
                    return await fetch_batch(batch, batch_num)

            results = await asyncio.gather(*[
                fetch_with_semaphore(batch, i)
                for i, batch in enumerate(batches)
            ])

            # Об'єднуємо результати
            for result in results:
                features.extend(result)
        except Exception as e:
            logger.warning(
                f"Parallel batch fetch failed: {e}, falling back to sequential")
            # Fallback до послідовної обробки
            features = []
            for i, batch in enumerate(batches):
                try:
                    batch_features = sp.audio_features(batch)
                    if batch_features:
                        features.extend(batch_features)
                    else:
                        features.extend([None] * len(batch))
                except Exception as batch_error:
                    logger.warning(f"Batch {i} failed: {batch_error}")
                    features.extend([None] * len(batch))

        # Check if all features are None (likely 403 error)
        # If spotipy returns None values instead of raising exceptions
        if features and all(f is None for f in features):
            logger.warning(
                "All audio features returned None. This likely indicates "
                "a 403 Forbidden error (insufficient permissions). "
                "Returning empty list to trigger fallback behavior."
            )
            return []

        # Зберегти в кеш (тільки якщо успішно отримано більшість)
        if features and sum(1 for f in features if f is not None) > len(features) * 0.5:
            self._cache[cache_key] = (features, time.time())

        return features

    def clear_cache(self):
        """Очистити кеш."""
        self._cache.clear()
        logger.info("Cache cleared")

    def get_cache_stats(self) -> Dict:
        """Отримати статистику кешу."""
        return {
            "cache_size": len(self._cache),
            "cache_ttl": self._cache_ttl,
            "cached_keys": list(self._cache.keys())[:10]
        }
